### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by dukn** [sonvx/word2vecVN#1]
Em làm như hướng dẫn và bị lỗi này. Mọi người ai biết giúp em với. Tks

Traceback (most recent call last):
  File "Main.py", line 52, in <module>
    word2vec_model = Word2Vec.load_word2vec_format(model, binary=True)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 1420, in load_word2vec_format
    raise DeprecationWarning("Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.")
DeprecationWarning: Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.

**Comment by sonvx** [comment]
Em có thể sửa thế này hoặc pull origin master về. 
from gensim.models import KeyedVectors
word2vec_model = KeyedVectors.load_word2vec_format(model_path, binary=True)
