### ISSUE TITLE
The dictionary has some problem 

### ISSUE THREAD

**Issue by laynelee28** [sonvx/word2vecVN#2]
I download dictionary from https://drive.google.com/open?id=0B1GKSX6YCHXlakkzQ2plZVdUUE0 , It is in binary format, so I changed it to readable text file. 

It has almost 230,000 words, but a lot of words is in English and Japanese, there are not very much Vietnamese words in the file.

I think you may upload the wrong dictionary! Please check it!

**Comment by sonvx** [comment]
Hi there, 
You're correct. That was trained on Vietnamese wiki data.
I just updated the other link.
