### ISSUE TITLE
deal with unknow word

### ISSUE THREAD

**Issue by ThanhDucPham** [sonvx/word2vecVN#5]
In my work,when I tokenize words from news, there are many other words that is'nt appear in your vocab, so what should do with that words? I found word 'unknow' in your vocab but I'm not sure that is what I needed.
Hope your response soon. Many thanks!

**Comment by gioinguyen1305** [comment]
> In my work,when I tokenize words from news, there are many other words that is'nt appear in your vocab, so what should do with that words? I found word 'unknow' in your vocab but I'm not sure that is what I needed.
> Hope your response soon. Many thanks!

maybe useful for you: https://github.com/yuvalpinter/Mimick

**Comment by ThanhDucPham** [comment]
Many thanks!! I wonder why they not use a UNKNOW or NUM( for number) vector embedding for these words is not appear in the vocab?

**Comment by sonvx** [comment]
@ThanhDucPham : you can take the average of character embeddings for unknown works. It's a simple but effective approach. If you use ETNLP [1], it does the job automatically when the word doesn't exist in the vocab.
[1] https://github.com/vietnlp/etnlp.
