### ISSUE TITLE
other-models-n-examples

### ISSUE THREAD

**Issue by phamthuha0970** [sonvx/word2vecVN#8]
Anh ơi em tải dữ liệu từ link https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.vi.vec không được ạ.
Anh có thể cho e xin link tải hoặc hướng dẫn em cách xây dựng được không ạ.
Em cảm ơn!

**Comment by sonvx** [comment]
Em dùng thẳng file .bin nhé: https://thiaisotajppub.s3-ap-northeast-1.amazonaws.com/publicfiles/wiki.vi.model.bin.gz
