### ISSUE TITLE
Giúp em với ạ

### ISSUE THREAD

**Issue by vominhthongss** [sonvx/word2vecVN#9]
Anh cho em hỏi, theo em được biết Word2Vec có 2 kiến trúc Cbow và Skipgram. 
Em không biết các bộ:
  1. Model trained on Vietnamese Wiki
  2. Model trained on Le et al.'s data (window-size 5, 400 dims)
  3. Model trained on Le et al.'s data (window-size 2, 300 dims)
Anh train theo kiến trúc nào ạ?
Em xin cảm ơn!

**Comment by sonvx** [comment]
@vominhthongss tất cả đều Cbow em nhé.
